### ISSUE TITLE
Pgen ps vita sound glitches

### ISSUE THREAD

**Issue by bellonok** [Cpasjuste/pemu#230]
Playing pier solar I noticed sound trembling, any one know how to solve it?

**Comment by MayanKoyote** [comment]
PCM track-list stutters not as badly as FM. But it's still noticeable.

**Comment by Cpasjuste** [comment]
Hi, this should be fixed in next release, thanks for the report.

**Comment by Cpasjuste** [comment]
Hi,

This should be fixed in [latest release](https://github.com/Cpasjuste/pemu/releases/tag/v6.7), please let me know if it's not the case so i can re-open this issue!

**Comment by MayanKoyote** [comment]
Got some time to test it out. Mainly listened to the theme song "Reja Town".

_**Setup №1:**_
psvita: PCH-1108, fw 3.60, psvsd, PSVita-StorageMgr v3.2.
rom: .md extension packed into .zip archive, MD5: e9c76d40d733165b5e499f43d4032e13.
enchanced soundtrack: no enchanced soundtrack file.
(So only FM track-list available).

**case 1.1. FM track-list:**
- 1.1.1 pGen v6.6: heavy/strong, very noticeable music stuttering/crunching (and epic slowdowns) is present during logos and in the game.
- 1.1.2 pGen v6.7.1: light/moderate, noticeable music stuttering/crunching (and slowdowns) is present during logos and in the game. Sounds _much_ better than pGen v6.6.

_**Setup №2:**_
psvita: PCH-1108, fw 3.60, psvsd, PSVita-StorageMgr v3.2.
rom: .md extension packed into .zip archive, MD5: e9c76d40d733165b5e499f43d4032e13.
enchanced soundtrack: .iso format, size 349224960 bytes (the one that was available for download from the game's official forum, "non-size-fixed" version), MD5: 5eda50f2626625ef16bf5623a9bb835d.
(PCM track-list is enabled by default from the beginning if ESD is present)

**case 2.1. PCM track-list (default):**
- 2.1.1. pGen v6.6: light/moderate, noticeable music stuttering/crunching is present during logos and in the game.
- 2.1.2. pGen v6.7.1: almost perfect. **>> This! <<**

**case 2.2. FM track-list (switching (ingame options) from PCM track-list to FM track-list):**
- 2.2.1. pGen v6.6: heavy/strong, very noticeable music stuttering/crunching (and epic slowdowns) is present during logos and in the game. Starts same as case 1.1.1, but gets worse and worse over time, then resets to "same as case 1.1.1" and again (cycling)
- 2.2.2. pGen v6.7.1: same as 1.1.2: light/moderate, noticeable music stuttering/crunching  (and slowdowns) is present during logos and in the game. Sounds _much_ better than pGen v6.6.

And the most interesting thing is for dessert (both setups):
**case 3.1. FM track-list ('START' was pressed during "watermelon-eating guy" logo to disable disks support** (I think that's exactly what it does, because after this only FM track-list is available)):

- 3.1.1. pGen v6.6: starts almost perfect, but gets worse and worse over time, then resets to "almost perfect" and again (cycling). Sometimes very noticeable music stuttering/crunching (and epic slowdowns) is present during logos and in the game.
- 3.1.2. pGen v6.7.1: almost perfect. **>> This! <<** (Exactly. Witchcraft!).
