### ISSUE TITLE
Add a CPU boost option to all pEMU emulators

### ISSUE THREAD

**Issue by Nono0000** [Cpasjuste/pemu#41]
Bonjour CPASJUSTE,

On Switch, when playing roms like the Metal Slug series (pFBN), we have huge slow downs as soon as many sprites are on the screen.
On pSNES, I have similar issues with U.N Squadron.
This is true in mobile and docked situations.

That is not directly linked to your work but more related to emulator core optimization. Could we imagine a similar option to "CPU Boost" you implemented in pPLAY? (Can you reuse any code from there?)

I think this could greatly improve the experience on certain games.
This option could be selected on rom basis.

Thanks a lot for your work.

**Comment by Cpasjuste** [comment]
Hi,

I'm not sure for un-squadron but for metal slug this is not a problem with the Nintendo Switch CPU speed. They are running like this on real hardware, you can make some research and you should find that. Since emulators tries to be accurate as possible, it does also suffer from this problem. There is some emulators which allow (68k?) emulated cpu overclock, but this comes with other problems from what I remember.

**Comment by Nono0000** [comment]
Bad idea then.
On my PC (neorageX) I see few slowdowns for those games but nothing compared to what I experiment on switch. Most probably because neorageX is not really cycle accurate.

I close the ticket.
Sorry for the inconvenience.
