### ISSUE TITLE
[pSNES] Game does not load when video snap is playing

### ISSUE THREAD

**Issue by Panja0** [Cpasjuste/pemu#52]
Using pSNES 4.4 from the Homebrew Store.
I'm having troubles running games when using video snaps.

The problem seems to occur when using video snaps.
I have removed the video snap for Super Mario World and the game loads as normal.
The problem seems to be when the video snap is loaded (which runs normally as far as I can see) the game cannot be started anymore..

If I open the game, when the video snap is playing, it won't load the game.
When I switch back to a different game, than switch to Super Mario World again but press the A button to load the game before the video plays (only showing the title png file), the game loads without problems.

I have tried the video snap from here:
https://github.com/Cpasjuste/pemu/blob/master/psnes/README.MD
But also tried the video snap from EmuMovies.

Nintendo Switch
Firmware: 10.0.3
Atmosphere: 0.12.0
Using EmuNAND

**Comment by Cpasjuste** [comment]
Hi,

Thanks for the report. Do you know if this problem only occurs with the "Super Mario World" video snap? Does other games are able to load normally when the video snap is playing ?

**Comment by Panja0** [comment]
Thanks for the **ULTRA FAST** reply.  

Just tried a few others.
And indeed it seems to be a problem with all titles I throw at it, but only when the video snap is playing.

**Comment by Cpasjuste** [comment]
Ok thanks, for the testing. This is probably a recent bug as i think it was working fine before. I will take a look as soon as possible (probably a few days :) ).

**Comment by Panja0** [comment]
I have tried/test pNES and the bug does not seem to be present in pNES, only in pSNES.

Thanks for your support!
At the moment I use a workaround. Just open the game before the video snap plays.
And when you have a video snap playing, just switch to a different game, switch back to the game you want to play and press A directly to load the game.

**Comment by Cpasjuste** [comment]
Else for now you can set a very high value for the "video_snap_delay" option in the menu (in seconds) so video snaps doesn't play at all.

**Comment by Panja0** [comment]
Yes, that's a workaround as well which I thought about. Thanks!

**Comment by Cpasjuste** [comment]
By the way, are you using a fat32 or exfat sdcard?

**Comment by Panja0** [comment]
FAT32! :-)

**Comment by Panja0** [comment]
Just to make sure it's not a problem on my side I have shutdown the Switch and rebooted it = same problem.

Also removed and re-installed pSNES = same problem.

Just FYI.

**Comment by CaptainCPS** [comment]
Hello just to add a bit info to this issue, since I think is probably related. When I try to load Super Mario World, it takes a few minutes to load, like 3 minutes~ (displaying the "Please Wait" message). Other games take like 5 to 10 seconds to load. I find it strange that it takes so long, since is such a small file.

Here are my specs:

pSNES: v4.4 (tested both from NSP Install and NRO, full memory mode / no applet mode)
Previews: Yes (downloaded from here)
Video Previews: No
NSwitch: SXOS v2.9.5 (EMUNAND)
SD: 128GB (FAT32)
SNES romset: "No-Intro - Nintendo - Super Nintendo Entertainment System (2017-05-29)"

**Comment by CaptainCPS** [comment]
I have to confirm yet, and do some more testing, but I formatted another SD Card (256GB) as FAT32, but instead of using 4KB (4096 bytes) for allocation unit size, I used 32KB (32768 bytes) and now it loads in just a like 3 seconds!

I will do more testing and see if the slow loading and such is caused by the allocation unit size when formatting the SD card.

**Comment by Cpasjuste** [comment]
> I have to confirm yet, and do some more testing, but I formatted another SD Card (256GB) as FAT32, but instead of using 4KB (4096 bytes) for allocation unit size, I used 32KB (32768 bytes) and now it loads in just a like 3 seconds!
> 
> I will do more testing and see if the slow loading and such is caused by the allocation unit size when formatting the SD card.

Hi ghost,

Does this also fix the game not loading after a video preview was loaded ?

**Comment by Panja0** [comment]
It does not fix it for me @Cpasjuste 
Tried it as well and still having crashes/rom not loading when video preview is loaded.
I have this with pNES and pSNES but not with pFBA.

**Comment by Cpasjuste** [comment]
Hi,

I can't reproduce this problem anymore. Be sure to run hbmenu in extended (ram) mode
